import Link from 'next/link'
import { Control } from './Control';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const res = await fetch('http://localhost:9999/topics', {cache: 'no-store'});
  const topics = await res.json();
  // console.log(topics);

  return (
    <html lang="en">
      <body>
        <div>
          <input type='text' placeholder='search' />
          <h1><Link href='/'>WEB</Link></h1>
          <ol>
            {topics.map((t)=>{
              return <li><Link href={`/read/${t.id}`}>{t.title}</Link></li>
            })}
          </ol>
          {children}
          <Control />  
        </div>
      </body>
    </html>
  )
}
